//! Parameter alias → canonical-name resolution, ported VERBATIM from the C++
//! `LightGBM/src/io/config_auto.cpp::Config::alias_table()` (lines 10-181).
//!
//! The full table is ported (cheap), even for out-of-v1-scope canonicals, so
//! the drift-checker can assert coverage and so alias resolution matches C++
//! exactly. Resolution is pass-through: an alias maps to its canonical name; a
//! canonical name (or any unknown string) resolves to itself — matching the
//! C++ behavior where unknown params produce a warning, never a hard error
//! (see `ParameterAlias::KeyAliasTransform` in config.h).

/// The verbatim alias → canonical pairs from `config_auto.cpp::alias_table()`.
///
/// Order matches the C++ source; each `(alias, canonical)` entry is exact.
pub const ALIAS_TABLE: &[(&str, &str)] = &[
    ("config_file", "config"),
    ("task_type", "task"),
    ("objective_type", "objective"),
    ("app", "objective"),
    ("application", "objective"),
    ("loss", "objective"),
    ("boosting_type", "boosting"),
    ("boost", "boosting"),
    ("train", "data"),
    ("train_data", "data"),
    ("train_data_file", "data"),
    ("data_filename", "data"),
    ("test", "valid"),
    ("valid_data", "valid"),
    ("valid_data_file", "valid"),
    ("test_data", "valid"),
    ("test_data_file", "valid"),
    ("valid_filenames", "valid"),
    ("num_iteration", "num_iterations"),
    ("n_iter", "num_iterations"),
    ("num_tree", "num_iterations"),
    ("num_trees", "num_iterations"),
    ("num_round", "num_iterations"),
    ("num_rounds", "num_iterations"),
    ("nrounds", "num_iterations"),
    ("num_boost_round", "num_iterations"),
    ("n_estimators", "num_iterations"),
    ("max_iter", "num_iterations"),
    ("shrinkage_rate", "learning_rate"),
    ("eta", "learning_rate"),
    ("num_leaf", "num_leaves"),
    ("max_leaves", "num_leaves"),
    ("max_leaf", "num_leaves"),
    ("max_leaf_nodes", "num_leaves"),
    ("tree", "tree_learner"),
    ("tree_type", "tree_learner"),
    ("tree_learner_type", "tree_learner"),
    ("num_thread", "num_threads"),
    ("nthread", "num_threads"),
    ("nthreads", "num_threads"),
    ("n_jobs", "num_threads"),
    ("device", "device_type"),
    ("random_seed", "seed"),
    ("random_state", "seed"),
    ("hist_pool_size", "histogram_pool_size"),
    ("min_data_per_leaf", "min_data_in_leaf"),
    ("min_data", "min_data_in_leaf"),
    ("min_child_samples", "min_data_in_leaf"),
    ("min_samples_leaf", "min_data_in_leaf"),
    ("min_sum_hessian_per_leaf", "min_sum_hessian_in_leaf"),
    ("min_sum_hessian", "min_sum_hessian_in_leaf"),
    ("min_hessian", "min_sum_hessian_in_leaf"),
    ("min_child_weight", "min_sum_hessian_in_leaf"),
    ("sub_row", "bagging_fraction"),
    ("subsample", "bagging_fraction"),
    ("bagging", "bagging_fraction"),
    ("pos_sub_row", "pos_bagging_fraction"),
    ("pos_subsample", "pos_bagging_fraction"),
    ("pos_bagging", "pos_bagging_fraction"),
    ("neg_sub_row", "neg_bagging_fraction"),
    ("neg_subsample", "neg_bagging_fraction"),
    ("neg_bagging", "neg_bagging_fraction"),
    ("subsample_freq", "bagging_freq"),
    ("bagging_fraction_seed", "bagging_seed"),
    ("sub_feature", "feature_fraction"),
    ("colsample_bytree", "feature_fraction"),
    ("sub_feature_bynode", "feature_fraction_bynode"),
    ("colsample_bynode", "feature_fraction_bynode"),
    ("extra_tree", "extra_trees"),
    ("early_stopping_rounds", "early_stopping_round"),
    ("early_stopping", "early_stopping_round"),
    ("n_iter_no_change", "early_stopping_round"),
    ("max_tree_output", "max_delta_step"),
    ("max_leaf_output", "max_delta_step"),
    ("reg_alpha", "lambda_l1"),
    ("l1_regularization", "lambda_l1"),
    ("reg_lambda", "lambda_l2"),
    ("lambda", "lambda_l2"),
    ("l2_regularization", "lambda_l2"),
    ("min_split_gain", "min_gain_to_split"),
    ("rate_drop", "drop_rate"),
    ("topk", "top_k"),
    ("mc", "monotone_constraints"),
    ("monotone_constraint", "monotone_constraints"),
    ("monotonic_cst", "monotone_constraints"),
    ("monotone_constraining_method", "monotone_constraints_method"),
    ("mc_method", "monotone_constraints_method"),
    ("monotone_splits_penalty", "monotone_penalty"),
    ("ms_penalty", "monotone_penalty"),
    ("mc_penalty", "monotone_penalty"),
    ("feature_contrib", "feature_contri"),
    ("fc", "feature_contri"),
    ("fp", "feature_contri"),
    ("feature_penalty", "feature_contri"),
    ("fs", "forcedsplits_filename"),
    ("forced_splits_filename", "forcedsplits_filename"),
    ("forced_splits_file", "forcedsplits_filename"),
    ("forced_splits", "forcedsplits_filename"),
    ("verbose", "verbosity"),
    ("model_input", "input_model"),
    ("model_in", "input_model"),
    ("model_output", "output_model"),
    ("model_out", "output_model"),
    ("save_period", "snapshot_freq"),
    ("linear_trees", "linear_tree"),
    ("max_bins", "max_bin"),
    ("subsample_for_bin", "bin_construct_sample_cnt"),
    ("data_seed", "data_random_seed"),
    ("is_sparse", "is_enable_sparse"),
    ("enable_sparse", "is_enable_sparse"),
    ("sparse", "is_enable_sparse"),
    ("is_enable_bundle", "enable_bundle"),
    ("bundle", "enable_bundle"),
    ("is_pre_partition", "pre_partition"),
    ("two_round_loading", "two_round"),
    ("use_two_round_loading", "two_round"),
    ("has_header", "header"),
    ("label", "label_column"),
    ("weight", "weight_column"),
    ("group", "group_column"),
    ("group_id", "group_column"),
    ("query_column", "group_column"),
    ("query", "group_column"),
    ("query_id", "group_column"),
    ("ignore_feature", "ignore_column"),
    ("blacklist", "ignore_column"),
    ("cat_feature", "categorical_feature"),
    ("categorical_column", "categorical_feature"),
    ("cat_column", "categorical_feature"),
    ("categorical_features", "categorical_feature"),
    ("is_save_binary", "save_binary"),
    ("is_save_binary_file", "save_binary"),
    ("is_predict_raw_score", "predict_raw_score"),
    ("predict_rawscore", "predict_raw_score"),
    ("raw_score", "predict_raw_score"),
    ("is_predict_leaf_index", "predict_leaf_index"),
    ("leaf_index", "predict_leaf_index"),
    ("is_predict_contrib", "predict_contrib"),
    ("contrib", "predict_contrib"),
    ("predict_result", "output_result"),
    ("prediction_result", "output_result"),
    ("predict_name", "output_result"),
    ("prediction_name", "output_result"),
    ("pred_name", "output_result"),
    ("name_pred", "output_result"),
    ("convert_model_file", "convert_model"),
    ("num_classes", "num_class"),
    ("unbalance", "is_unbalance"),
    ("unbalanced_sets", "is_unbalance"),
    ("metrics", "metric"),
    ("metric_types", "metric"),
    ("output_freq", "metric_freq"),
    ("training_metric", "is_provide_training_metric"),
    ("is_training_metric", "is_provide_training_metric"),
    ("train_metric", "is_provide_training_metric"),
    ("ndcg_eval_at", "eval_at"),
    ("ndcg_at", "eval_at"),
    ("map_eval_at", "eval_at"),
    ("map_at", "eval_at"),
    ("num_machine", "num_machines"),
    ("local_port", "local_listen_port"),
    ("port", "local_listen_port"),
    ("machine_list_file", "machine_list_filename"),
    ("machine_list", "machine_list_filename"),
    ("mlist", "machine_list_filename"),
    ("workers", "machines"),
    ("nodes", "machines"),
];

/// Resolve a parameter name to its canonical name.
///
/// - An alias (left column of [`ALIAS_TABLE`]) → its canonical name.
/// - A canonical name or any unknown string → itself (pass-through).
///
/// Mirrors the C++ `KeyAliasTransform` lookup: an unknown parameter is NOT an
/// error here — the soft "Unknown parameter" diagnostic is handled (or ignored)
/// at the call site, never a hard failure.
pub fn resolve_alias(name: &str) -> &str {
    for (alias, canonical) in ALIAS_TABLE {
        if *alias == name {
            return canonical;
        }
    }
    name
}
