// rng_capture.cpp
//
// Dev-only C++ capture harness for the LightGBM-rs oracle (D-07/D-14).
//
// Builds against the pinned, read-only LightGBM submodule and exercises the
// reference `LightGBM::Random` LCG over a RANDOMIZED, diverse set of cases
// derived deterministically from ONE recorded MASTER SEED (no wall-clock / OS
// entropy, so regen is idempotent). It writes a line-delimited golden file
// (`rng_sequence.txt`) that the Rust `oracle-harness` parity test replays with
// NO C++ toolchain at normal test time.
//
// Determinism contract (mirrored in REFERENCE_MANIFEST.md): the MASTER_SEED and
// the case-generation algorithm below are the single source of randomness. The
// xtask Rust driver passes the master seed + counts on argv so the manifest and
// the capture agree.
//
// Fixture format (line-delimited, '#'-prefixed comments ignored by the reader):
//   MASTER_SEED <seed>
//   COUNTS rng=<n_rng> sample=<n_sample>
//   RNG seed=<s> int16=<a;b;...> int32=<a;b;...> float=<bits;bits;...> int=<a;b;...>
//   SAMPLE seed=<s> N=<n> K=<k> result=<v0;v1;...>
//
// `float` values are emitted as the raw little-endian f32 bit pattern (a u32 in
// decimal) so the Rust side can assert exact-bit f32 equality with zero parsing
// rounding. Integer draws are emitted as decimals and compared exactly.

#include <LightGBM/utils/random.h>

#include <cmath>
#include <cstdint>
#include <cstring>
#include <fstream>
#include <iostream>
#include <string>
#include <vector>

namespace {

// Number of draws emitted per RNG case, per method.
constexpr int kDrawsPerMethod = 32;

// Reinterpret an f32 as its raw u32 bit pattern (exact, lossless).
uint32_t FloatBits(float f) {
  uint32_t bits;
  std::memcpy(&bits, &f, sizeof(bits));
  return bits;
}

// A tiny deterministic generator used ONLY to derive the case set (seeds, N, K)
// from the master seed. We reuse LightGBM::Random itself so the derivation is
// trivially reproducible on the Rust side (which owns the same Random port).
// This is NOT the system under test for those derivation draws — the SUT is the
// per-case Random(case_seed) below.
struct CaseGen {
  LightGBM::Random rng;
  explicit CaseGen(int master_seed) : rng(master_seed) {}
  // A 31-bit-ish positive seed value for a case.
  int NextSeed() { return rng.NextInt(1, 2000000000); }
};

}  // namespace

int main(int argc, char** argv) {
  // argv: <out_path> <master_seed> <n_rng_cases> <n_sample_cases>
  if (argc != 5) {
    std::cerr << "usage: rng_capture <out_path> <master_seed> <n_rng_cases> "
                 "<n_sample_cases>\n";
    return 2;
  }
  const std::string out_path = argv[1];
  const int master_seed = std::stoi(argv[2]);
  const int n_rng = std::stoi(argv[3]);
  const int n_sample = std::stoi(argv[4]);

  std::ofstream out(out_path, std::ios::binary | std::ios::trunc);
  if (!out) {
    std::cerr << "error: cannot open output file: " << out_path << "\n";
    return 1;
  }

  out << "# LightGBM-rs RNG golden set (randomized-at-capture, D-14)\n";
  out << "# Generated by xtask/cpp/rng_capture.cpp against the pinned LightGBM "
         "submodule.\n";
  out << "# Reproducible from MASTER_SEED via LightGBM::Random; see "
         "REFERENCE_MANIFEST.md.\n";
  out << "MASTER_SEED " << master_seed << "\n";
  out << "COUNTS rng=" << n_rng << " sample=" << n_sample << "\n";

  // ----- RNG cases: many random LCG seeds, multi-method draw sequences. -----
  {
    CaseGen gen(master_seed);
    for (int c = 0; c < n_rng; ++c) {
      const int seed = gen.NextSeed();
      LightGBM::Random r(seed);

      // Fixed, documented order: kDrawsPerMethod of each method, in this order:
      //   int16 (NextShort 0..32768), int32 (NextInt 0..2^30), float, int.
      // Note: each call advances the SAME shared state x, so the order is
      // load-bearing and the Rust replay must match it exactly.
      out << "RNG seed=" << seed << " int16=";
      for (int i = 0; i < kDrawsPerMethod; ++i) {
        if (i) out << ";";
        out << r.NextShort(0, 32768);
      }
      out << " int32=";
      for (int i = 0; i < kDrawsPerMethod; ++i) {
        if (i) out << ";";
        out << r.NextInt(0, 1073741824);  // [0, 2^30)
      }
      out << " float=";
      for (int i = 0; i < kDrawsPerMethod; ++i) {
        if (i) out << ";";
        out << FloatBits(r.NextFloat());
      }
      out << " int=";
      for (int i = 0; i < kDrawsPerMethod; ++i) {
        if (i) out << ";";
        out << r.NextInt(-1000, 1000);
      }
      out << "\n";
    }
  }

  // ----- Sample cases: randomized (N, K) straddling K > N/log2(K). -----
  {
    CaseGen gen(master_seed + 1);  // distinct stream from the RNG cases
    for (int c = 0; c < n_sample; ++c) {
      const int seed = gen.NextSeed();
      // Randomize N in a broad range, then choose K to land on both sides of
      // and near the streaming/set branch boundary K > N/log2(K).
      const int N = gen.rng.NextInt(4, 4096);
      // Boundary K* solves K = N/log2(K); approximate by sweeping, then pick K
      // randomly within [1, N-1] biased toward the boundary so both branches
      // and the near-boundary region are exercised across the set.
      int K;
      const int mode = gen.rng.NextInt(0, 3);
      if (mode == 0) {
        // small K -> set branch
        K = gen.rng.NextInt(1, std::max(2, N / 8));
      } else if (mode == 1) {
        // large K -> streaming branch
        K = gen.rng.NextInt(std::max(1, N / 2), N);
      } else {
        // near the boundary: approximate K* ~ N/log2 of a guess, iterate once
        double guess = static_cast<double>(N) / std::log2(std::max(2, N / 4));
        int kb = static_cast<int>(guess);
        int lo = std::max(1, kb - 3);
        int hi = std::min(N - 1, kb + 3);
        K = (hi > lo) ? gen.rng.NextInt(lo, hi + 1) : lo;
      }
      if (K < 1) K = 1;
      if (K >= N) K = N - 1;

      LightGBM::Random r(seed);
      std::vector<int> result = r.Sample(N, K);

      out << "SAMPLE seed=" << seed << " N=" << N << " K=" << K << " result=";
      for (size_t i = 0; i < result.size(); ++i) {
        if (i) out << ";";
        out << result[i];
      }
      out << "\n";
    }
  }

  out.flush();
  if (!out) {
    std::cerr << "error: failed while writing output\n";
    return 1;
  }
  std::cerr << "rng_capture: wrote " << n_rng << " RNG cases + " << n_sample
            << " Sample cases to " << out_path << "\n";
  return 0;
}
