//! Phase-29 29-05 (OCX-05, Task 1) — the ONE end-to-end proof gate on the EXACT
//! spike-072 A/B corpus.
//!
//! # What this gate proves
//!
//! At master-before-Phase-29 the opt-in on-device arm (`LGBM_CUDA_ON_DEVICE=1`) trained a
//! **13-tree model** on this exact corpus — boosting stopped when the f32 serial root-fold
//! bias (spike-072 item 13) compounded to NaN grad/hess by iter 13, and GBDT's C++-faithful
//! no-split pop-loop silently truncated the model. The Phase-28 "first not-slower cell"
//! (0.931×) therefore compared a 13-tree model against a 100-tree host baseline
//! (`28-AB-RESULTS.md`, invalidated per spike-072 Results 1-4).
//!
//! With 29-01..29-04 landed (exact f64 root fold on every GPU lane / config-bound
//! admissibility gate / mfb-cell preservation / non-finite tripwire), the identical corpus
//! and config must now train **100/100 trees** with every leaf value finite and bounded.
//! This gate is the committed, executed regression proof of that.
//!
//! # Method (spike-072 lessons, do NOT weaken)
//!
//! - The tree count is asserted on the **EMITTED MODEL TEXT** (`Tree=` headers), NEVER on a
//!   per-tree-denominator counter. Spike-072's core method lesson: `launches/100`,
//!   `syncs/100`, `rootbuild/100` all LIE when the train stops early — 880 syncs was 13 full
//!   grows, not 100 stunted ones. This test contains NO assertion on launch/sync/rootbuild.
//! - The subprocess route (not an in-process env flip) is REQUIRED: `LGBM_CUDA_ON_DEVICE`
//!   is `OnceLock`-cached and read ONCE per process (`lgbm-compute/src/lib.rs`), so an
//!   in-process test cannot flip it between the two arms. Each arm is a fresh
//!   `bench_real` process with the env set — byte-identical to the spike's zero-code repro.
//! - The leaf bound is a GENEROUS structural bound (|v| <= 100.0). The healthy value is
//!   pinned EMPIRICALLY by the host control arm run in this same gate: the host reference
//!   arm's max |leaf| on this corpus is ~10.32 (and the on-device arm is bit-identical to it,
//!   29-03). NOTE: spike-072 item 5 cited "~0.26" — that was a different, earlier-tree probe
//!   measurement; the emitted 100-tree model's max |leaf| on this corpus is ~10.32 on BOTH
//!   arms, so the bound is anchored to the observed host max, not the stale 0.26 figure. 100.0
//!   sits ~10× above the healthy host max and ~13× below the spike-072 blow-up signature
//!   (1.27e3 -> ±inf), so it detects degeneracy WITHOUT coupling to the f32 envelope — this is
//!   a tree-COUNT + finiteness gate, not a value-parity gate (the u64-integer anchor in
//!   `on_device_integer_anchor.rs` owns exact parity).
//!
//! # Cost + how to run
//!
//! Two 100-iter 500k×50 binary trains on the local GPU (~tens of minutes on the APU) — hence
//! `#[ignore]`. Run ONCE:
//!
//! ```text
//! cargo test -p oracle-harness --test on_device_e2e_ab_corpus --features rocm -- --ignored --nocapture
//! ```
//!
//! Provenance: the corpus is generated by
//! `.planning/spikes/072-ondevice-stunted-trees-repro-bisect/gen_corpus.py 500000 50 <tsv>`
//! (`make_classification(500000, 50, random_state=42)`, %.17g round-trip exact) and driven
//! through the same `train_raw` path via `crates/lgbm/examples/bench_real.rs` (binary,
//! num_leaves=31, lr=0.1, 100 iters, max_bin=255 — the exact A/B params). The corpus is
//! cached in the temp dir keyed by shape, so re-runs skip regeneration.

#![cfg(feature = "rocm")]

use std::path::{Path, PathBuf};
use std::process::Command;

const NUM_SAMPLES: usize = 500_000;
const NUM_FEATURES: usize = 50;
const EXPECT_TREES: usize = 100;
/// Structural degeneracy bound. Anchored to the host control arm's EMPIRICALLY measured max
/// |leaf| (~10.32 on this 100-tree model; the on-device arm is bit-identical, 29-03) — NOT
/// spike-072 item 5's stale "~0.26" (a different, earlier-tree probe). 100.0 sits ~10× above
/// the healthy host max and ~13× below the spike-072 blow-up signature (1.27e3 -> ±inf), so it
/// detects degeneracy without coupling to the f32 envelope.
const LEAF_ABS_BOUND: f64 = 100.0;

/// Repo root = `<repo>/crates/oracle-harness` -> up two.
fn repo_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .and_then(Path::parent)
        .expect("oracle-harness is <repo>/crates/oracle-harness")
        .to_path_buf()
}

/// Ensure the exact spike-072 corpus exists (cached in temp, keyed by shape). Returns `None`
/// with a LOUD skip message if the `.venv` python or its deps are absent (never a false pass).
fn ensure_corpus(repo_root: &Path) -> Option<PathBuf> {
    let cache = std::env::temp_dir().join(format!(
        "lgbm_spike072_ab_corpus_{NUM_SAMPLES}x{NUM_FEATURES}.tsv"
    ));
    if cache.exists() && std::fs::metadata(&cache).map(|m| m.len() > 0).unwrap_or(false) {
        eprintln!("[e2e-gate] reusing cached corpus: {}", cache.display());
        return Some(cache);
    }

    let venv_py = repo_root.join(".venv/bin/python");
    if !venv_py.exists() {
        eprintln!(
            "[e2e-gate] SKIP: {} not found — the uv .venv (sklearn/numpy) is required to \
             generate the spike-072 corpus. This is a SKIP, not a pass.",
            venv_py.display()
        );
        return None;
    }
    let gen_script = repo_root
        .join(".planning/spikes/072-ondevice-stunted-trees-repro-bisect/gen_corpus.py");
    assert!(gen_script.exists(), "gen_corpus.py missing at {}", gen_script.display());

    eprintln!(
        "[e2e-gate] generating corpus {NUM_SAMPLES}x{NUM_FEATURES} -> {} (one-time)",
        cache.display()
    );
    let out = Command::new(&venv_py)
        .arg(&gen_script)
        .arg(NUM_SAMPLES.to_string())
        .arg(NUM_FEATURES.to_string())
        .arg(&cache)
        .current_dir(repo_root)
        .output()
        .expect("spawn gen_corpus.py");
    if !out.status.success() {
        let stderr = String::from_utf8_lossy(&out.stderr);
        // Missing sklearn/numpy surfaces here — LOUD skip, not a false pass.
        if stderr.contains("ModuleNotFoundError") || stderr.contains("ImportError") {
            eprintln!(
                "[e2e-gate] SKIP: gen_corpus.py failed on a missing python dep (sklearn/numpy):\n{stderr}"
            );
            let _ = std::fs::remove_file(&cache);
            return None;
        }
        panic!("gen_corpus.py failed: {stderr}");
    }
    eprintln!("[e2e-gate] {}", String::from_utf8_lossy(&out.stdout).trim());
    Some(cache)
}

/// Build the `bench_real` example with the rocm feature (the on-device path needs the hip
/// runtime compiled in). Panics on build failure.
fn build_bench_real(repo_root: &Path) {
    eprintln!("[e2e-gate] cargo build --release -p lgbm --example bench_real --features rocm");
    let status = Command::new(env!("CARGO"))
        .args([
            "build",
            "--release",
            "-p",
            "lgbm",
            "--example",
            "bench_real",
            "--features",
            "rocm",
        ])
        .current_dir(repo_root)
        .status()
        .expect("spawn cargo build");
    assert!(status.success(), "cargo build of bench_real (rocm) failed");
}

/// Run `bench_real <corpus> tsv-label0 binary dump-model` with `LGBM_CUDA_ON_DEVICE=<on>`,
/// returning the emitted model text (stdout). Subprocess = sidesteps the OnceLock env cache.
fn run_bench_real(repo_root: &Path, corpus: &Path, on_device: &str) -> String {
    let bin = repo_root.join("target/release/examples/bench_real");
    assert!(bin.exists(), "bench_real binary missing at {}", bin.display());
    eprintln!("[e2e-gate] LGBM_CUDA_ON_DEVICE={on_device} bench_real dump-model (100-iter train)…");
    let out = Command::new(&bin)
        .arg(corpus)
        .arg("tsv-label0")
        .arg("binary")
        .arg("dump-model")
        .env("LGBM_CUDA_ON_DEVICE", on_device)
        .current_dir(repo_root)
        .output()
        .expect("spawn bench_real");
    assert!(
        out.status.success(),
        "bench_real (LGBM_CUDA_ON_DEVICE={on_device}) exited non-zero: {}\nstderr:\n{}",
        out.status,
        String::from_utf8_lossy(&out.stderr)
    );
    String::from_utf8(out.stdout).expect("model text is utf-8")
}

/// Parse the emitted LightGBM v4 model text: return `(tree_count, all_leaf_values)`.
/// Tree count = number of `Tree=` headers (the EMITTED MODEL, never a counter). Leaf values
/// = every value on every `leaf_value=` line.
fn parse_model(model: &str) -> (usize, Vec<f64>) {
    let mut tree_count = 0usize;
    let mut leaves: Vec<f64> = Vec::new();
    for line in model.lines() {
        if line.starts_with("Tree=") {
            tree_count += 1;
        } else if let Some(rest) = line.strip_prefix("leaf_value=") {
            for tok in rest.split_whitespace() {
                leaves.push(tok.parse::<f64>().unwrap_or_else(|_| {
                    panic!("leaf_value token '{tok}' does not parse as f64")
                }));
            }
        }
    }
    (tree_count, leaves)
}

fn max_abs(leaves: &[f64]) -> f64 {
    leaves.iter().fold(0.0_f64, |m, &v| m.max(v.abs()))
}

#[test]
#[ignore = "expensive: two 100-iter 500k×50 GPU trains (~tens of min). Run: cargo test -p oracle-harness --test on_device_e2e_ab_corpus --features rocm -- --ignored --nocapture"]
fn on_device_ab_corpus_trains_100_finite_bounded_trees() {
    let repo_root = repo_root();
    let corpus = match ensure_corpus(&repo_root) {
        Some(c) => c,
        None => return, // LOUD skip already printed (absent venv/deps) — not a false pass.
    };
    build_bench_real(&repo_root);

    // On-device arm (the arm under test) + host control arm (harness sanity).
    let model_on = run_bench_real(&repo_root, &corpus, "1");
    let model_host = run_bench_real(&repo_root, &corpus, "0");

    let (trees_on, leaves_on) = parse_model(&model_on);
    let (trees_host, leaves_host) = parse_model(&model_host);
    let max_on = max_abs(&leaves_on);
    let max_host = max_abs(&leaves_host);

    eprintln!(
        "[e2e-gate] RESULT: on-device trees={trees_on} max|leaf|={max_on:.6} | \
         host trees={trees_host} max|leaf|={max_host:.6} (bound={LEAF_ABS_BOUND})"
    );

    // (1) The emitted on-device model has EXACTLY 100 trees — the spike-072 regression proof.
    assert_eq!(
        trees_on, EXPECT_TREES,
        "on-device arm emitted {trees_on} trees (want {EXPECT_TREES}); the spike-072 13-tree \
         collapse (or an early-stop regression) has returned — see 28-AB-RESULTS.md banner"
    );
    // (2) The host control arm trains 100 trees too (harness sanity).
    assert_eq!(
        trees_host, EXPECT_TREES,
        "host control arm emitted {trees_host} trees (want {EXPECT_TREES}); the harness/corpus \
         is wrong, not the on-device path"
    );
    // (3) Every on-device leaf value is finite and within the structural bound.
    for (i, &v) in leaves_on.iter().enumerate() {
        assert!(
            v.is_finite() && v.abs() <= LEAF_ABS_BOUND,
            "on-device leaf #{i} = {v} is non-finite or |v| > {LEAF_ABS_BOUND} — the \
             spike-072 blow-up signature (1.27e3 -> ±inf)"
        );
    }
    // (4) Structural sanity: the host arm is likewise finite + bounded (proves the bound is
    //     honest, not slack the on-device arm barely clears).
    for (i, &v) in leaves_host.iter().enumerate() {
        assert!(
            v.is_finite() && v.abs() <= LEAF_ABS_BOUND,
            "host leaf #{i} = {v} is non-finite or |v| > {LEAF_ABS_BOUND} — unexpected on the host arm"
        );
    }

    eprintln!(
        "[e2e-gate] PASS: on-device arm trained {EXPECT_TREES}/{EXPECT_TREES} finite-bounded \
         trees on the exact spike-072 corpus (max|leaf| on-device={max_on:.6}, host={max_host:.6})."
    );
}
