//! If-else C++ codegen (G1) — emits a standalone, compilable `.cpp` predict
//! source for a `GbdtModel`, semantically mirroring `Tree::predict` /
//! `GbdtModel::predict_raw` (`tree.rs:193-290`, `ensemble.rs:90-102`). Mirrors
//! C++ `Tree::NodeToIfElse` / `GBDT::ModelToIfElse` / `SaveModelToIfElse`
//! (`src/io/tree.cpp`, `src/boosting/gbdt_model_text.cpp`).
//!
//! # Byte-exactness caveat (SPEC-G1-4)
//! The `LightGBM/` 4.6 C++ tree is **absent** in this sandbox and the
//! `lightgbm==4.6.0` pip wheel exports `GBDT::ModelToIfElse` ONLY as a private
//! C++ method — there is no C-API entry point and no `lightgbm` CLI binary in
//! the wheel to invoke `Config.convert_model`. A byte-exact golden `.cpp`
//! therefore cannot be captured in this environment (same class of blocker as
//! G4/G5's C++-checkout dependency). This module's exact C++ text layout
//! (function/variable names, brace style, helper prototypes) is an
//! **independent, semantically-faithful** emission — NOT verified byte-for-
//! byte against the real `ModelToIfElse` output. What IS verified: the
//! generated code, compiled and executed, reproduces
//! [`crate::ensemble::GbdtModel::predict_raw`] bit-for-bit on the CPU f64
//! anchor (`oracle-harness/tests/ifelse_codegen_parity.rs`,
//! `ifelse_codegen_functional_validation`).
//!
//! # Float formatting
//! Every threshold / leaf value is emitted via [`crate::format::format_g17`]
//! (DEC-1) — never `to_string()`/`ryu`.
//!
//! # Missing/default-left routing
//! Each internal node mirrors `Tree::numerical_decision` (`tree.rs:193-212`)
//! EXACTLY:
//! - `missing_type == None` (0): a NaN input is substituted to `0.0`, then
//!   compared normally against `threshold` — NOT routed to the default branch.
//! - `missing_type == Zero` (1): a NaN input is substituted to `0.0`; any
//!   value within `±kZeroThreshold` of zero (substituted or genuine) routes to
//!   the `default_left`/`default_right` branch; otherwise compared normally.
//! - `missing_type == NaN` (2): a NaN input (NOT substituted) routes to the
//!   default branch; otherwise compared normally.
//!
//! Categorical splits mirror `Tree::categorical_decision` (`tree.rs:214-235`):
//! NaN or a negative truncated value routes right; otherwise membership in the
//! node's bitset (`Common::FindInBitset`, re-emitted as a local `uint32_t[]`
//! literal + a file-scope `FindInBitset` helper) selects left/right.

use crate::ensemble::GbdtModel;
use crate::format::format_g17;
use crate::tree::Tree;

/// C++ `#define kCategoricalMask (1)` (`tree.h:20`) — bit0 of `decision_type`.
const CATEGORICAL_MASK: i8 = 1;
/// C++ `#define kDefaultLeftMask (2)` (`tree.h:21`) — bit1 of `decision_type`.
const DEFAULT_LEFT_MASK: i8 = 2;
/// `Tree::GetMissingType` values (`tree.h:274`, bits2-3 of `decision_type`).
const MISSING_NONE: i8 = 0;
const MISSING_ZERO: i8 = 1;

/// `lgbm_core::types::K_ZERO_THRESHOLD` (1e-35) — C++ `kZeroThreshold`, the
/// `Tree::IsZero` epsilon (`tree.rs:170-175`).
const K_ZERO_THRESHOLD: f64 = lgbm_core::types::K_ZERO_THRESHOLD;

const HEADER: &str = "\
// Generated by lgbm-model codegen_cpp (G1 if-else codegen).
// Semantically mirrors Tree::predict / GBDT::PredictRaw; NOT byte-verified
// against real `GBDT::ModelToIfElse` output (see module doc: no C-API/CLI
// export of `convert_model` in the lightgbm==4.6.0 pip wheel).
#include <cmath>
#include <cstdint>

";

const FIND_IN_BITSET_HELPER: &str = "\
// C++ `Common::FindInBitset` (`common.h:836`).
static inline bool FindInBitset(const uint32_t* bits, int bits_len, int32_t pos) {
  int i1 = pos / 32;
  if (i1 >= bits_len) { return false; }
  int i2 = pos % 32;
  return ((bits[i1] >> i2) & 1) != 0;
}

";

/// Emit the C++ predict-function body for one tree: nested `if`/`else` over
/// `split_feature`/`threshold`/`decision_type`, returning `leaf_value` at the
/// leaves (`%.17g` via [`format_g17`]). Mirrors C++ `Tree::NodeToIfElse`.
///
/// A constant (`num_leaves <= 1`) tree emits a single `return` — mirroring
/// `Tree::predict`'s `num_leaves > 1` guard (`tree.rs:279-290`), which skips
/// the node walk entirely for a single-leaf tree.
///
/// Linear-tree (`is_linear`) leaf codegen is OUT OF SCOPE for G1 (SPEC §2 —
/// no linear mention in the G1 typed contract); a linear tree still emits its
/// (incorrect, constant-only) `leaf_value`, documented here as a known gap.
#[must_use]
pub fn tree_to_cpp(tree: &Tree, tree_index: usize) -> String {
    let mut s = String::new();
    s.push_str(&format!(
        "double PredictTree{tree_index}(const double* arr) {{\n"
    ));
    if tree.num_leaves <= 1 {
        let leaf_value = tree.leaf_value.first().copied().unwrap_or(0.0);
        s.push_str(&format!("  return {};\n", format_g17(leaf_value)));
    } else {
        node_to_cpp(tree, 0, tree_index, &mut s, 1);
    }
    s.push_str("}\n");
    s
}

/// Recursive pre-order node emitter (mirrors `Tree::numerical_decision`'s
/// exact substitution/default/compare order for each internal node).
fn node_to_cpp(tree: &Tree, index: i32, tree_index: usize, out: &mut String, indent: usize) {
    let pad = "  ".repeat(indent);
    if index < 0 {
        let leaf = (!index) as usize;
        out.push_str(&format!(
            "{pad}return {};\n",
            format_g17(tree.leaf_value[leaf])
        ));
        return;
    }
    let node = index as usize;
    let decision_type = tree.decision_type[node];
    let feat = tree.split_feature[node];

    if (decision_type & CATEGORICAL_MASK) > 0 {
        emit_categorical_node(tree, node, feat, tree_index, out, indent, &pad);
        return;
    }

    let missing_type = (decision_type >> 2) & 3;
    let default_left = (decision_type & DEFAULT_LEFT_MASK) > 0;
    let threshold = format_g17(tree.threshold[node]);
    let var = format!("fval_{node}");

    out.push_str(&format!("{pad}double {var} = arr[{feat}];\n"));

    match missing_type {
        MISSING_NONE => {
            // NaN -> 0, then a plain compare (no default-branch routing).
            out.push_str(&format!(
                "{pad}if (std::isnan({var})) {{ {var} = 0.0; }}\n"
            ));
            out.push_str(&format!("{pad}if ({var} <= {threshold}) {{\n"));
            node_to_cpp(tree, tree.left_child[node], tree_index, out, indent + 1);
            out.push_str(&format!("{pad}}} else {{\n"));
            node_to_cpp(tree, tree.right_child[node], tree_index, out, indent + 1);
            out.push_str(&format!("{pad}}}\n"));
        }
        MISSING_ZERO => {
            // NaN -> 0, then |fval| <= kZeroThreshold routes default; else compare.
            let k_zero = format_g17(K_ZERO_THRESHOLD);
            out.push_str(&format!(
                "{pad}if (std::isnan({var})) {{ {var} = 0.0; }}\n"
            ));
            out.push_str(&format!(
                "{pad}if ({var} >= -{k_zero} && {var} <= {k_zero}) {{\n"
            ));
            let default_branch = if default_left {
                tree.left_child[node]
            } else {
                tree.right_child[node]
            };
            node_to_cpp(tree, default_branch, tree_index, out, indent + 1);
            out.push_str(&format!("{pad}}} else if ({var} <= {threshold}) {{\n"));
            node_to_cpp(tree, tree.left_child[node], tree_index, out, indent + 1);
            out.push_str(&format!("{pad}}} else {{\n"));
            node_to_cpp(tree, tree.right_child[node], tree_index, out, indent + 1);
            out.push_str(&format!("{pad}}}\n"));
        }
        _ => {
            // MISSING_NAN: fval NOT substituted; a genuine NaN routes default.
            out.push_str(&format!("{pad}if (std::isnan({var})) {{\n"));
            let default_branch = if default_left {
                tree.left_child[node]
            } else {
                tree.right_child[node]
            };
            node_to_cpp(tree, default_branch, tree_index, out, indent + 1);
            out.push_str(&format!("{pad}}} else if ({var} <= {threshold}) {{\n"));
            node_to_cpp(tree, tree.left_child[node], tree_index, out, indent + 1);
            out.push_str(&format!("{pad}}} else {{\n"));
            node_to_cpp(tree, tree.right_child[node], tree_index, out, indent + 1);
            out.push_str(&format!("{pad}}}\n"));
        }
    }
}

/// Categorical node emitter — mirrors `Tree::categorical_decision`
/// (`tree.rs:214-235`): NaN or a negative truncated value routes RIGHT;
/// otherwise bitset membership (`Common::FindInBitset`) selects left/right.
#[allow(clippy::too_many_arguments)]
fn emit_categorical_node(
    tree: &Tree,
    node: usize,
    feat: i32,
    tree_index: usize,
    out: &mut String,
    indent: usize,
    pad: &str,
) {
    let cat_idx = tree.threshold[node] as i32 as usize;
    let lo = tree.cat_boundaries[cat_idx] as usize;
    let hi = tree.cat_boundaries[cat_idx + 1] as usize;
    let bitset = &tree.cat_threshold[lo..hi];
    let bitset_name = format!("kCatBitset_{tree_index}_{node}");
    let words: String = bitset
        .iter()
        .map(|b| format!("{b}u"))
        .collect::<Vec<_>>()
        .join(",");
    out.push_str(&format!(
        "{pad}static const uint32_t {bitset_name}[] = {{{words}}};\n"
    ));
    let var = format!("fval_{node}");
    out.push_str(&format!("{pad}double {var} = arr[{feat}];\n"));
    out.push_str(&format!(
        "{pad}if (std::isnan({var}) || static_cast<int32_t>({var}) < 0 || \
         !FindInBitset({bitset_name}, {}, static_cast<int32_t>({var}))) {{\n",
        bitset.len()
    ));
    node_to_cpp(tree, tree.right_child[node], tree_index, out, indent + 1);
    out.push_str(&format!("{pad}}} else {{\n"));
    node_to_cpp(tree, tree.left_child[node], tree_index, out, indent + 1);
    out.push_str(&format!("{pad}}}\n"));
}

/// Emit the full standalone C++ source: `#include`s, one `PredictTree{i}`
/// function per tree ([`tree_to_cpp`]), and a `PredictRaw`-style summation
/// over the ensemble, `num_tree_per_iteration`-strided across boosting
/// iterations. Mirrors C++ `GBDT::ModelToIfElse`/`SaveModelToIfElse`.
///
/// # Shrinkage
/// Per-tree leaf values are ALREADY shrinkage-scaled at training time
/// (`Tree::shrinkage`, `tree.rs:1074-1095`, multiplies `leaf_value_` in
/// place; the stored `shrinkage` field is metadata only). `PredictRaw`
/// therefore sums `PredictTree{i}(arr)` directly with NO extra multiply —
/// mirroring [`crate::ensemble::GbdtModel::predict_raw`] exactly.
#[must_use]
pub fn model_to_cpp(model: &GbdtModel) -> String {
    let mut s = String::new();
    s.push_str(HEADER);
    if model.trees.iter().any(|t| t.num_cat > 0) {
        s.push_str(FIND_IN_BITSET_HELPER);
    }
    for (i, tree) in model.trees.iter().enumerate() {
        s.push_str(&tree_to_cpp(tree, i));
        s.push('\n');
    }

    let ntpi = model.num_tree_per_iteration.max(1) as usize;
    let num_iteration = if ntpi > 0 { model.trees.len() / ntpi } else { 0 };

    s.push_str(
        "// PredictRaw: num_tree_per_iteration-strided sum over boosting iterations.\n\
         // `out` must have room for num_tree_per_iteration doubles.\n",
    );
    s.push_str("void PredictRaw(const double* arr, double* out) {\n");
    for k in 0..ntpi {
        s.push_str(&format!("  out[{k}] = 0;\n"));
    }
    for i in 0..num_iteration {
        for k in 0..ntpi {
            let idx = i * ntpi + k;
            s.push_str(&format!("  out[{k}] += PredictTree{idx}(arr);\n"));
        }
    }
    s.push_str("}\n");
    s
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ensemble::GbdtModel;
    use crate::tree::Tree;

    /// A minimal 2-leaf numeric-split tree: root split on feature 0 at
    /// threshold 1.5, default-left, missing None.
    fn tiny_tree() -> Tree {
        Tree {
            num_leaves: 2,
            num_cat: 0,
            left_child: vec![-1],
            right_child: vec![-2],
            split_feature: vec![0],
            threshold: vec![1.5],
            decision_type: vec![2], // default-left, missing None
            split_gain: vec![0.0],
            leaf_value: vec![10.0, 20.0],
            leaf_weight: vec![1.0, 1.0],
            leaf_count: vec![1, 1],
            internal_value: vec![0.0],
            internal_weight: vec![0.0],
            internal_count: vec![2],
            cat_boundaries: vec![],
            cat_threshold: vec![],
            shrinkage: 1.0,
            is_linear: false,
            linear: None,
            leaf_depth: vec![0, 0],
            leaf_parent: vec![-1, -1],
            split_feature_inner: vec![-1],
            threshold_in_bin: vec![0],
        }
    }

    /// SPEC-G1-1: the emitted fragment contains an `if (` / `<=` comparison
    /// against the `format_g17` threshold literal, and returns the
    /// `format_g17` leaf values on both branches.
    #[test]
    fn tree_to_cpp_numeric() {
        let t = tiny_tree();
        let cpp = tree_to_cpp(&t, 0);
        assert!(cpp.starts_with("double PredictTree0(const double* arr) {\n"));
        assert!(cpp.contains("if ("), "missing if(: {cpp}");
        assert!(cpp.contains("<="), "missing <=: {cpp}");
        assert!(
            cpp.contains(&format_g17(1.5)),
            "threshold not format_g17: {cpp}"
        );
        assert!(
            cpp.contains(&format!("return {};", format_g17(10.0))),
            "left leaf not format_g17: {cpp}"
        );
        assert!(
            cpp.contains(&format!("return {};", format_g17(20.0))),
            "right leaf not format_g17: {cpp}"
        );
        assert!(cpp.trim_end().ends_with('}'));
    }

    /// A single-leaf (constant) tree skips the node walk entirely.
    #[test]
    fn tree_to_cpp_single_leaf_is_constant_return() {
        let mut t = tiny_tree();
        t.num_leaves = 1;
        t.leaf_value = vec![7.0];
        let cpp = tree_to_cpp(&t, 3);
        assert!(cpp.contains(&format!("return {};", format_g17(7.0))));
        assert!(!cpp.contains("if ("), "constant tree must not branch: {cpp}");
    }

    fn two_tree_model() -> GbdtModel {
        GbdtModel {
            trees: vec![tiny_tree(), tiny_tree()],
            num_class: 1,
            num_tree_per_iteration: 1,
            label_index: 0,
            max_feature_idx: 0,
            average_output: false,
            objective_string: Some("regression".to_string()),
            feature_names: "Column_0".to_string(),
            feature_infos: "[0.5:1.5]".to_string(),
            monotone_constraints: None,
            trailer: None,
        }
    }

    /// SPEC-G1-2: two per-tree function definitions + a `PredictRaw`
    /// summation referencing both.
    #[test]
    fn model_to_cpp_two_tree() {
        let m = two_tree_model();
        let cpp = model_to_cpp(&m);
        assert_eq!(
            cpp.matches("double PredictTree0(const double* arr) {").count(),
            1
        );
        assert_eq!(
            cpp.matches("double PredictTree1(const double* arr) {").count(),
            1
        );
        assert!(cpp.contains("void PredictRaw(const double* arr, double* out) {"));
        assert!(cpp.contains("out[0] += PredictTree0(arr);"));
        assert!(cpp.contains("out[0] += PredictTree1(arr);"));
    }

    /// A model with a categorical split pulls in the `FindInBitset` helper.
    #[test]
    fn model_to_cpp_categorical_pulls_in_bitset_helper() {
        let mut cat_tree = tiny_tree();
        cat_tree.num_cat = 1;
        cat_tree.decision_type = vec![CATEGORICAL_MASK]; // categorical, not default-left
        cat_tree.threshold = vec![0.0]; // cat_idx 0
        cat_tree.cat_boundaries = vec![0, 1];
        cat_tree.cat_threshold = vec![0b110]; // categories {1,2} route left
        let m = GbdtModel {
            trees: vec![cat_tree],
            num_class: 1,
            num_tree_per_iteration: 1,
            ..two_tree_model()
        };
        let cpp = model_to_cpp(&m);
        assert!(cpp.contains("FindInBitset"));
        assert!(cpp.contains("static const uint32_t kCatBitset_0_0[] = {6u};"));
    }
}
